-- lab-hard/db/pg/seed.sql — Postgres 17 HARD. Idempotent reset seed.
DROP TABLE IF EXISTS verification_token;
DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS config;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS canary;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  email VARCHAR(128) NOT NULL,
  secret VARCHAR(256) NOT NULL,
  is_admin SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE verification_token (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NULL REFERENCES users(id) ON DELETE CASCADE,
  token VARCHAR(255) NOT NULL UNIQUE,
  api_key VARCHAR(255) NOT NULL,
  expires_at TIMESTAMPTZ NULL
);

CREATE TABLE credentials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credential_name VARCHAR(128) NOT NULL UNIQUE,
  credential_values JSONB NOT NULL
);

CREATE TABLE config (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  param_name VARCHAR(128) NOT NULL UNIQUE,
  environment_variables JSONB NOT NULL
);

CREATE TABLE profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nick VARCHAR(256) NOT NULL,
  bio VARCHAR(512) NOT NULL DEFAULT ''
);

CREATE TABLE canary (
  id INT PRIMARY KEY,
  marker VARCHAR(64) NOT NULL
);

INSERT INTO users (username, email, secret, is_admin) VALUES
  ('alice', 'alice@example.com', 'flag-hard-alice-7f3a2c91e4', 0),
  ('bob',   'bob@example.com',   'flag-hard-bob-b81d44f0a2',   0),
  ('admin', 'admin@example.com', 'flag-hard-admin-9c4e1d77f0', 1);

INSERT INTO verification_token (user_id, token, api_key) VALUES
  (1, 'litellm-token-alice-01', 'sk-litellm-alice-HARD-001'),
  (3, 'litellm-token-admin-01', 'sk-litellm-admin-HARD-002');

INSERT INTO credentials (credential_name, credential_values) VALUES
  ('openai-prod', '{"openai_api_key": "sk-proj-hard-AAA111", "model": "gpt-4o"}'),
  ('anthropic-prod', '{"anthropic_api_key": "sk-ant-hard-BBB222"}');

INSERT INTO config (param_name, environment_variables) VALUES
  ('prod', '{"OPENAI_API_KEY": "sk-proj-hard-AAA111", "ANTHROPIC_API_KEY": "sk-ant-hard-BBB222", "AWS_SECRET_ACCESS_KEY": "aws-hard-CCC333"}');

INSERT INTO profiles (nick, bio) VALUES ('alice', 'hello'), ('bob', 'world');

INSERT INTO canary (id, marker) VALUES (1, 'untouched');

SELECT setval(pg_get_serial_sequence('users','id'), 3);
SELECT setval(pg_get_serial_sequence('verification_token','id'), 2);
SELECT setval(pg_get_serial_sequence('credentials','id'), 2);
SELECT setval(pg_get_serial_sequence('config','id'), 1);
SELECT setval(pg_get_serial_sequence('profiles','id'), 2);
