-- lab-hard/db/oracle/seed.sql — Oracle 23ai HARD (profil opt-in).
-- Exécuté via sqlplus/sqlcl sur FREEPDB1, schéma courant.
BEGIN EXECUTE IMMEDIATE 'DROP TABLE verification_token CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE credentials CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_config CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE profiles CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE canary CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username VARCHAR2(64) NOT NULL UNIQUE,
  email VARCHAR2(128) NOT NULL,
  secret VARCHAR2(256) NOT NULL,
  is_admin NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_admin IN (0,1))
);

CREATE TABLE verification_token (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NULL REFERENCES users(id) ON DELETE CASCADE,
  token VARCHAR2(255) NOT NULL UNIQUE,
  api_key VARCHAR2(255) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE credentials (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  credential_name VARCHAR2(128) NOT NULL UNIQUE,
  credential_values JSON NOT NULL
);

CREATE TABLE app_config (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  param_name VARCHAR2(128) NOT NULL UNIQUE,
  environment_variables JSON NOT NULL
);

CREATE TABLE profiles (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nick VARCHAR2(256) NOT NULL,
  bio VARCHAR2(512) DEFAULT '' NOT NULL
);

CREATE TABLE canary (
  id NUMBER PRIMARY KEY,
  marker VARCHAR2(64) NOT NULL
);

INSERT INTO users (id, username, email, secret, is_admin) VALUES (1, 'alice', 'alice@example.com', 'flag-hard-alice-7f3a2c91e4', 0);
INSERT INTO users (id, username, email, secret, is_admin) VALUES (2, 'bob', 'bob@example.com', 'flag-hard-bob-b81d44f0a2', 0);
INSERT INTO users (id, username, email, secret, is_admin) VALUES (3, 'admin', 'admin@example.com', 'flag-hard-admin-9c4e1d77f0', 1);
INSERT INTO verification_token (user_id, token, api_key) VALUES (1, 'litellm-token-alice-01', 'sk-litellm-alice-HARD-001');
INSERT INTO verification_token (user_id, token, api_key) VALUES (3, 'litellm-token-admin-01', 'sk-litellm-admin-HARD-002');
INSERT INTO credentials (credential_name, credential_values) VALUES ('openai-prod', '{"openai_api_key": "sk-proj-hard-AAA111", "model": "gpt-4o"}');
INSERT INTO credentials (credential_name, credential_values) VALUES ('anthropic-prod', '{"anthropic_api_key": "sk-ant-hard-BBB222"}');
INSERT INTO app_config (param_name, environment_variables) VALUES ('prod', '{"OPENAI_API_KEY": "sk-proj-hard-AAA111", "ANTHROPIC_API_KEY": "sk-ant-hard-BBB222", "AWS_SECRET_ACCESS_KEY": "aws-hard-CCC333"}');
INSERT INTO profiles (nick, bio) VALUES ('alice', 'hello');
INSERT INTO profiles (nick, bio) VALUES ('bob', 'world');
INSERT INTO canary (id, marker) VALUES (1, 'untouched');
COMMIT;
